name: proof_of_fix

on:
  workflow_dispatch:

jobs:
  proof:
    name: Proof of Fix
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --cap-add=SYS_ADMIN

    steps:
      - name: Checkout Reproduction Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Download Built WebdriverIO
        uses: actions/download-artifact@v4
        with:
          name: webdriverio-build
          path: ./webdriverio-fork

      - name: Unzip Built WebdriverIO
        run: |
          cd webdriverio-fork
          unzip webdriverio-build.zip -d extracted
          cd extracted/packages/webdriverio
          npm link

      - name: Link Built WebdriverIO into Repro Project
        run: npm link webdriverio

      - name: Install Reproduction Project Dependencies
        run: npm install

      - name: Install Chrome and Chromedriver
        run: npm run install-chrome-base

      - name: Run Tests
        run: npm test
