name: proof_of_fix

on:
  workflow_dispatch:

jobs:
  build_webdriverio:
    name: Build WebdriverIO Fork
    runs-on: ubuntu-latest

    outputs:
      artifact-name: webdriverio-build

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Clone WebdriverIO Fork
        run: |
          git clone --depth=1 https://github.com/ArtMathArt/webdriverio.git webdriverio-fork

      - name: Install dependencies and build
        run: |
          export SHELL=/bin/bash
          cd webdriverio-fork
          pnpm install
          pnpm setup
          pnpm build

      - name: Create Build Archive
        run: |
          cd webdriverio-fork
          zip -q -r webdriverio-build.zip packages/*/build packages/*/cjs

      - name: Upload WebdriverIO Build Archive
        uses: actions/upload-artifact@v4
        with:
          name: webdriverio-build
          path: webdriverio-fork/webdriverio-build.zip

  proof_of_fix:
    name: Proof of Fix
    runs-on: ubuntu-latest
    needs: build_webdriverio
    container:
      image: ghcr.io/puppeteer/puppeteer:latest
      options: --cap-add=SYS_ADMIN --user root

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Install Project Dependencies
        run: npm install
      
      - name: Install Chrome and Chromedriver
        run: npm run install-chrome-base

      - name: Download WebdriverIO Build
        uses: actions/download-artifact@v4
        with:
          name: webdriverio-build
          path: ./webdriverio-fork

      - name: Unzip Built WebdriverIO
        run: |
          cd webdriverio-fork
          unzip webdriverio-build.zip -d extracted
      
      - name: Replace WebdriverIO Build Folder
        run: |
          rm -rf node_modules/webdriverio/build
          cp -r webdriverio-fork/extracted/packages/webdriverio/build node_modules/webdriverio/

      - name: Run Tests
        run: su pptruser -c "npm test"
